# NOTE: this is not production deployment script. It's just for testing purposes
version: '3.9'
services:
  community-dashboard:
    build: .
    pull_policy: always
    ports:
      - 3000:3000
    environment:
      NEXT_PUBLIC_WS_BASE_URL: 'ws://localhost:4000/api/v1'
      NEXT_PUBLIC_BASE_URL: 'http://localhost:4000/api/v1'
    restart: on-failure
    depends_on:
      - community-api

  community-api:
    image: kotalco/community-api:latest
    pull_policy: always
    ports:
      - 4000:4000
    environment:
      KOTAL_API_SERVER_PORT: 0.0.0.0:4000
      MOCK: 'true'
    restart: on-failure
